(deftheme ai "The AI color theme based on http://flatuicolors.com")

(let ((ai-alizarin "#e74c3c")
      (ai-amethyst "#9b59b6")
      (ai-asbestos "#7f8c8d")
      (ai-belize-hole "#2980b9")
      (ai-black-1 "#1c1c1c")
      (ai-black "#333332")
      (ai-clear-red "#f1e1e0")
      (ai-emerald "#2ecc71")
      (ai-gray "#f2f2f2")
      (ai-green-sea "#16a085")
      (ai-midnight-blue "#2c3e50")
      (ai-moss "#a7ffe0")
      (ai-orange "#f39c12")
      (ai-peter-river "#3498db")
      (ai-pumpkin "#d35400")
      (ai-silver "#bdc3c7")
      (ai-wet-asphalt "#34495e")
      (ai-wisteria "#8e44ad"))

  (custom-theme-set-faces
   'ai
   `(default ((t (:foreground ,ai-black :background ,ai-gray))))
   `(font-lock-preprocessor-face ((t (:foreground ,ai-black))))
   `(font-lock-type-face ((t (:foreground ,ai-black))))

   `(font-lock-builtin-face ((t (:foreground ,ai-black-1))))
   `(font-lock-comment-face ((t (:foreground ,ai-wet-asphalt))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,ai-wet-asphalt))))
   `(font-lock-constant-face ((t (:foreground ,ai-black-1))))
   `(font-lock-doc-face ((t (:foreground ,ai-belize-hole))))
   `(font-lock-function-name-face ((t (:foreground ,ai-black))))
   `(font-lock-keyword-face ((t (:foreground ,ai-black-1))))
   `(font-lock-string-face ((t (:foreground ,ai-belize-hole))))
   `(font-lock-variable-name-face ((t (:foreground ,ai-black))))
   `(region ((t (:background ,ai-moss))))
   `(fringe ((t (:foreground ,ai-black :background ,ai-gray))))

   `(mode-line ((t (:foreground ,ai-gray :background ,ai-black :box nil))))
   `(mode-line-inactive ((t (:foreground ,ai-black :background ,ai-silver :box nil))))
   `(minibuffer-prompt ((t (:foreground ,ai-black))))
   `(ido-first-match ((t (:foreground ,ai-green-sea :weight bold))))
   `(ido-only-match ((t (:foreground ,ai-amethyst :weight bold))))
   `(ido-subdir ((t (:foreground ,ai-midnight-blue))))

   `(show-paren-match ((t (:background nil :underline ,ai-peter-river))))
   `(show-paren-mismatch ((t (:foreground ,ai-alizarin :background nil :underline ,ai-alizarin))))

   `(rainbow-delimiters-depth-1-face ((t (:foreground ,ai-asbestos))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,ai-green-sea))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,ai-emerald))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,ai-belize-hole))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,ai-wisteria))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,ai-orange))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,ai-pumpkin))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,ai-alizarin))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,ai-midnight-blue))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,ai-alizarin :background ,ai-clear-red)))))

  (provide-theme 'ai))
