(deftheme dark "Dark color theme")

(let ((black "#292a30")
      (pink "#ef88b0")
      (white "#fcfcff")
      (cyan "#9ee9ea")
      (aquamarine "#c9f3ea")
      (grey-dark "#414246")
      (grey "#8e929b")
      (violet "#dbd1f9")
      (violet-dark "#c5c4fd")
      (green "#8eb2ab")
      (purple "#ac99da")
      (red "#f37f97")
      (red-dark "#ff4971"))
  (custom-theme-set-faces
   'dark
   `(default ((t (:foreground ,white :background ,black))))
   `(font-lock-builtin-face ((t (:foreground ,pink))))
   `(font-lock-comment-face ((t (:foreground ,grey))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,grey))))
   `(font-lock-constant-face ((t (:foreground ,pink))))
   `(font-lock-doc-face ((t (:foreground ,grey))))
   `(font-lock-keyword-face ((t (:foreground ,pink))))
   `(font-lock-function-name-face ((t (:foreground ,cyan))))
   `(font-lock-preprocessor-face ((t (:foreground ,cyan))))
   `(font-lock-string-face ((t (:foreground ,violet))))
   `(font-lock-type-face ((t (:foreground ,cyan))))
   `(font-lock-variable-name-face ((t (:foreground ,cyan))))
   `(error ((t (:foreground ,red))))
   `(warning ((t (:foreground ,violet))))
   `(success ((t (:foreground ,green))))
   `(fringe ((t (:foreground ,grey :background ,black))))
   `(minibuffer-prompt ((t (:foreground ,pink))))
   `(mode-line ((t (:foreground ,white :background ,grey-dark :box ,grey-dark))))
   `(mode-line-inactive ((t (:foreground ,grey :background ,grey-dark :box ,grey-dark))))
   `(mode-line-buffer-id ((t (:weight normal))))
   `(vertical-border ((t (:foreground "#414246"))))
   `(region ((t (:foreground ,white :background ,grey-dark )))) ;; "#C5C4FD"
   `(isearch ((t (:foreground ,white :background ,pink))))
   `(lazy-highlight ((t (:foreground ,grey-dark :background ,violet))))
   `(isearch-fail ((t (:background ,red))))
   `(ido-first-match ((t (:foreground ,purple :weight normal))))
   `(ido-only-match ((t (:foreground ,purple :weight normal))))
   `(ido-subdir ((t (:foreground ,violet))))
   `(diff-hl-insert ((t (:foreground ,green :background ,green))))
   `(diff-hl-change ((t (:foreground ,violet :background ,violet))))
   `(diff-hl-delete ((t (:foreground ,red :background ,red))))
   `(js2-external-variable ((t (:foreground ,pink))))
   `(js2-function-param ((t (:foreground ,aquamarine )))) ;
   `(flycheck-error ((t (:foreground ,red :underline (:color ,red :style line))))))
  (provide-theme 'dark))
