(deftheme gloom
  "Loose port of gloom: a dark and gloomy pastel color syntax theme for atom (https://atom.io/themes/gloom)")

(let ((aquamarine "#6DFEDF")
      (blue "#7AA5FF")
      (blue-dark "#292A44")
      (blue-really-dark "#212237")
      (cyan "#66D9EF")
      (magenta "#FF6F9F")
      (purple "#AE81FF")
      (red "#ED4781")
      (turquoise "#94F2E7")
      (turquoise-dark "#2DE0A7")
      (violet "#6D6DB5")
      (violet-dark "#3E3F66")
      (violet-light "#C5C4FD")
      (white "#FFFFFF")
      (white-dark "#DBDBFF")
      (yellow "#FFDB7D"))

  (custom-theme-set-faces
   'gloom
   `(default ((t (:foreground ,white-dark :background ,blue-dark))))
   `(link ((t (:foreground ,magenta :underline t))))
   `(highlight ((t (:foreground ,white :background ,magenta))))
   `(isearch ((t (:foreground ,blue-dark :background ,aquamarine))))
   `(isearch-fail ((t (:foreground ,white :background ,red))))
   `(lazy-highlight ((t (:foreground ,white-dark :background ,violet))))
   `(region ((t (:foreground ,white-dark :background ,red))))
   `(mode-line ((t (:foreground ,blue-dark :background ,turquoise :box ,turquoise))))
   `(mode-line-inactive ((t (:foreground ,violet-light :background ,violet-dark :box ,violet-dark))))
   `(mode-line-highlight ((t (:foreground ,white :background ,magenta :box ,magenta))))
   `(mode-line-buffer-id ((t (:weight normal))))
   `(header-line ((t (:foreground ,white :background ,blue))))
   `(vertical-border ((t (:foreground ,violet-dark))))
   `(minibuffer-prompt ((t (:foreground ,white-dark))))
   `(fringe ((t (:foreground ,violet  :background ,blue-dark))))
   `(cursor ((t (:background ,turquoise))))

   `(font-lock-builtin-face ((t (:foreground ,blue))))
   `(font-lock-comment-face ((t (:foreground ,violet))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,violet))))
   `(font-lock-constant-face ((t (:foreground ,magenta))))
   `(font-lock-doc-face ((t (:foreground ,violet))))
   `(font-lock-keyword-face ((t (:foreground ,blue))))
   `(font-lock-function-name-face ((t (:foreground ,white-dark))))
   `(font-lock-preprocessor-face ((t (:foreground ,white-dark))))
   `(font-lock-string-face ((t (:foreground ,aquamarine))))
   `(font-lock-type-face ((t (:foreground ,white-dark))))
   `(font-lock-variable-name-face ((t (:foreground ,white-dark))))

   `(ido-first-match ((t (:foreground ,blue :weight normal))))
   `(ido-only-match ((t (:foreground ,blue :weight normal))))
   `(ido-subdir ((t (:foreground ,aquamarine))))

   `(magit-header-line ((t (:foreground ,white :background ,blue))))
   `(magit-section-highlight ((t (:background ,blue-really-dark))))
   `(magit-diff-hunk-heading ((t (:foreground ,violet :background nil))))
   `(magit-diff-hunk-heading-highlight ((t (:foreground ,purple :background ,blue-really-dark))))
   `(magit-diff-added ((t (:foreground ,turquoise-dark :background nil))))
   `(magit-diff-added-highlight ((t (:foreground ,turquoise-dark :background ,blue-really-dark))))
   `(magit-diff-removed ((t (:foreground ,red :background nil))))
   `(magit-diff-removed-highlight ((t (:foreground ,red :background ,blue-really-dark))))
   `(magit-diff-context ((t (:foreground ,white-dark :background nil))))
   `(magit-diff-context-highlight ((t (:foreground ,white-dark :background ,blue-really-dark))))
   `(magit-section-heading ((t (:foreground ,cyan)))) ;; used also in magit's headers—ensure it looks good there or use a similar color to the header bg so it gets inverted
   `(magit-hash ((t (:foreground ,aquamarine))))
   `(magit-branch-current ((t (:foreground ,yellow))))
   `(magit-branch-local ((t (:foreground ,blue))))
   `(magit-branch-remote-head ((t (:foreground ,purple))))
   `(magit-branch-remote ((t (:foreground ,purple))))
   `(magit-blame-highlight ((t (:foreground ,blue-really-dark :background ,violet-light)))))

  (provide-theme 'gloom))
