(deftheme ibdknox "The Ibdknox color theme ported from LightTable")

(let ((ibdknox-black "#202020")
      (ibdknox-grey-3 "#3b3f41")
      (ibdknox-grey-2 "#555555")
      (ibdknox-grey-1 "#616161")
      (ibdknox-grey  "#cccccc")
      (ibdknox-grey+1 "#bbbbbb")
      (ibdknox-grey+2 "#aaaaaa")
      (ibdknox-grey+3 "#f4f4f4")
      (ibdknox-blue-1 "#7999ac")
      (ibdknox-blue "#9ccccc")
      (ibdknox-cyan-1 "#41feff")
      (ibdknox-cyan "#52feff")
      (ibdknox-green "#49ff00")
      (ibdknox-green+1 "#47ff6a")
      (ibdknox-violet-1 "#9528ff")
      (ibdknox-violet "#7f6cff")
      (ibdknox-pink "#f700ff")
      (ibdknox-red-1 "#753432")
      (ibdknox-red "#f9372b")
      (ibdknox-red+1 "#fa8986"))


  (custom-theme-set-faces
   'ibdknox
   `(default ((t (:foreground ,ibdknox-grey :background ,ibdknox-black))))
   `(font-lock-preprocessor-face ((t (:foreground ,ibdknox-grey))))
   `(font-lock-type-face ((t (:foreground ,ibdknox-grey))))

   `(font-lock-builtin-face ((t (:foreground ,ibdknox-grey+2))))
   `(font-lock-comment-face ((t (:foreground ,ibdknox-blue-1))))
   `(font-lock-constant-face ((t (:foreground ,ibdknox-grey+2))))
   `(font-lock-doc-face ((t (:foreground ,ibdknox-blue))))
   `(font-lock-function-name-face ((t (:foreground ,ibdknox-grey))))
   `(font-lock-keyword-face ((t (:foreground ,ibdknox-grey+2))))
   `(font-lock-string-face ((t (:foreground ,ibdknox-blue))))
   `(font-lock-variable-name-face ((t (:foreground ,ibdknox-blue))))
   `(region ((t (:background ,ibdknox-grey-2))))
   `(fringe ((t (:foreground ,ibdknox-grey+3 :background ,ibdknox-black))))

   `(mode-line ((t (:foreground ,ibdknox-grey+3 :background ,ibdknox-grey-1 :box nil))))
   `(mode-line-inactive ((t (:foreground ,ibdknox-grey+1 :background ,ibdknox-grey-3 :box nil))))
   `(minibuffer-prompt ((t (:foreground ,ibdknox-blue))))
   `(ido-first-match ((t (:foreground ,ibdknox-green+1 :weight bold))))
   `(ido-only-match ((t (:foreground ,ibdknox-violet :weight bold))))
   `(ido-subdir ((t (:foreground ,ibdknox-grey+2))))

   ;; `(show-paren-match ((t (:inverse-video t :weight bold))))
   `(show-paren-match ((t (:background nil :underline ,ibdknox-cyan))))
   `(show-paren-mismatch ((t (:foreground ,ibdknox-red :background nil :underline ,ibdknox-red))))

   `(rainbow-delimiters-depth-1-face ((t (:foreground ,ibdknox-grey+2))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,ibdknox-green))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,ibdknox-green+1))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,ibdknox-cyan-1))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,ibdknox-violet))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,ibdknox-pink))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,ibdknox-violet-1))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,ibdknox-green+1))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,ibdknox-cyan-1))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,ibdknox-red+1 :background ,ibdknox-red-1))))

   `(web-mode-html-tag-bracket-face ((t (:foreground ,ibdknox-grey+2))))
   `(web-mode-html-tag-face ((t (:foreground ,ibdknox-grey+2))))
   `(web-mode-html-attr-name-face ((t (:foreground  ,ibdknox-grey))))
   `(web-mode-html-attr-value-face ((t (:foreground ,ibdknox-blue)))))

  (provide-theme 'ibdknox))
